// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC43XY6V6_x0lq_C3ylJv1Uq6a_wvsDK4',
    appId: '1:27257277371:web:f1cc3cc3a1be8912d2929e',
    messagingSenderId: '27257277371',
    projectId: 'dentca-6e31d',
    authDomain: 'dentca-6e31d.firebaseapp.com',
    storageBucket: 'dentca-6e31d.firebasestorage.app',
    measurementId: 'G-E09MYNCL7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvgVaS58NbvioqMpPwjWXyitqZbR8eUn8',
    appId: '1:27257277371:android:96ce054d54babeecd2929e',
    messagingSenderId: '27257277371',
    projectId: 'dentca-6e31d',
    storageBucket: 'dentca-6e31d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnNfyNYp_rRbK8EpdK7ZA9ELIf24yiXts',
    appId: '1:27257277371:ios:22f085be087a6e2ad2929e',
    messagingSenderId: '27257277371',
    projectId: 'dentca-6e31d',
    storageBucket: 'dentca-6e31d.firebasestorage.app',
    iosBundleId: 'com.example.appSpynaly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnNfyNYp_rRbK8EpdK7ZA9ELIf24yiXts',
    appId: '1:27257277371:ios:22f085be087a6e2ad2929e',
    messagingSenderId: '27257277371',
    projectId: 'dentca-6e31d',
    storageBucket: 'dentca-6e31d.firebasestorage.app',
    iosBundleId: 'com.example.appSpynaly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC43XY6V6_x0lq_C3ylJv1Uq6a_wvsDK4',
    appId: '1:27257277371:web:63cb82f842f8f1e7d2929e',
    messagingSenderId: '27257277371',
    projectId: 'dentca-6e31d',
    authDomain: 'dentca-6e31d.firebaseapp.com',
    storageBucket: 'dentca-6e31d.firebasestorage.app',
    measurementId: 'G-BGNRVPBKRJ',
  );

}